#!/usr/bin/env python3
"""Install static figure fragments according to the survey manifests."""

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
FIGURE_MANIFEST = ROOT / "data/figure-manifest.json"
SITE_MANIFEST = ROOT / "data/site-manifest.json"
CSS_OUTPUT = ROOT / "assets/figures.css"


def load_json(path, label):
    try:
        value = json.loads(path.read_text())
    except FileNotFoundError:
        raise SystemExit(f"{label} manifest does not exist: {path}")
    except json.JSONDecodeError as exc:
        raise SystemExit(f"invalid JSON in {label} manifest: {exc}")
    if not isinstance(value, dict):
        raise SystemExit(f"{label} manifest must be a JSON object")
    return value


def replace_figure(document, dom_id, markup):
    """Replace one non-nested figure carrying ``dom_id`` in ``document``."""
    opening = re.search(
        rf"<figure\b[^>]*\bid\s*=\s*(['\"]){re.escape(dom_id)}\1[^>]*>",
        document,
        re.I,
    )
    if not opening:
        return None
    end = re.search(r"</figure\s*>", document[opening.end():], re.I)
    if not end:
        return None
    stop = opening.end() + end.end()
    return document[:opening.start()] + markup.strip() + document[stop:]


def generated_css(records):
    chunks = []
    for record in records:
        css = (ROOT / record["css"]).read_text().strip()
        if css:
            chunks.append(
                f"/* ---- {record['id']} (Figure {record['display_number']}) ---- */\n{css}"
            )
    body = "\n\n".join(chunks)
    return (
        "/* Generated by tools/install-figures.py in figure-manifest order.\n"
        "   Edit the per-figure CSS files, not this file. */\n"
        + (f"\n{body}\n" if body else "")
    )


def verify_implemented_figures():
    result = subprocess.run(
        [sys.executable, str(ROOT / "tools/check-figures.py")],
        cwd=ROOT.parent,
        check=False,
    )
    if result.returncode:
        raise SystemExit(result.returncode)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="report replacements and generated CSS without writing any file",
    )
    args = parser.parse_args()

    verify_implemented_figures()
    figure_payload = load_json(FIGURE_MANIFEST, "figure")
    site_payload = load_json(SITE_MANIFEST, "site")
    figures = figure_payload.get("figures")
    fragments = site_payload.get("fragments")
    if not isinstance(figures, list) or not isinstance(fragments, list):
        raise SystemExit("manifests must contain figures and fragments lists")

    section_paths = {
        record.get("id"): record.get("fragment")
        for record in fragments
        if isinstance(record, dict) and record.get("kind") == "section"
    }
    implemented = [
        record
        for record in figures
        if isinstance(record, dict)
        and record.get("interactive") is False
        and record.get("status") == "implemented"
    ]
    planned = [
        record
        for record in figures
        if isinstance(record, dict)
        and record.get("interactive") is False
        and record.get("status") == "planned"
    ]

    documents = {}
    changed = set()
    placement_errors = []
    placements = []
    for record in implemented:
        semantic_id = record["id"]
        number = record["display_number"]
        destination = record["destination_section"]
        relative = section_paths.get(destination)
        if not relative:
            raise SystemExit(
                f"implemented {semantic_id} (Figure {number}) has no site-manifest destination {destination!r}"
            )
        path = ROOT / relative
        if not path.is_file():
            message = (
                f"implemented {semantic_id} (Figure {number}) -> {destination} ({relative}): "
                "destination fragment unavailable"
            )
            print(message)
            placement_errors.append(message)
            continue
        document = documents.setdefault(path, path.read_text())
        replacement = replace_figure(document, f"figure-{number}", (ROOT / record["fragment"]).read_text())
        if replacement is None:
            message = (
                f"implemented {semantic_id} (Figure {number}) -> {destination} ({relative}): "
                f"target figure-{number} unavailable"
            )
            print(message)
            placement_errors.append(message)
            continue
        documents[path] = replacement
        if replacement != document:
            changed.add(path)
        placement = (
            f"implemented {semantic_id} (Figure {number}) -> {destination} ({relative})"
        )
        placements.append(placement)
        if args.check:
            print(f"{placement}: would replace")

    for record in planned:
        missing = [key for key in ("fragment", "css") if not (ROOT / record[key]).is_file()]
        detail = "missing planned " + " and ".join(missing) if missing else "planned assets already present"
        print(f"planned {record['id']} (Figure {record['display_number']}): {detail}")

    css = generated_css(implemented)
    if placement_errors:
        print(
            f"installation blocked with {len(placement_errors)} placement problem(s):",
            file=sys.stderr,
        )
        for error in placement_errors:
            print(f"  - cannot place {error}", file=sys.stderr)
        raise SystemExit(1)
    if args.check:
        print(
            f"css: would generate {len(implemented)} implemented static figure(s) -> {CSS_OUTPUT}"
        )
        return
    for path in sorted(changed):
        path.write_text(documents[path])
    if not CSS_OUTPUT.exists() or CSS_OUTPUT.read_text() != css:
        CSS_OUTPUT.write_text(css)
    for placement in placements:
        print(f"{placement}: replaced")
    print(f"css: generated {len(implemented)} implemented static figure(s) -> {CSS_OUTPUT}")


if __name__ == "__main__":
    main()
