#!/usr/bin/env python3
"""Splice the hand-drawn section 2 figures into sec-02.html.

Each figure is authored as a standalone site/figures/figure-N.html holding one
complete <figure> element, with its scoped rules alongside in figure-N.css. That
split is what let five figures be drawn at once without colliding in one file,
and it keeps a figure re-editable on its own afterwards. This script is the
merge step, and it is re-runnable: it matches on the figure's id, so installing
a corrected figure is the same operation as installing it the first time.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIGS = ROOT / 'site/figures'
SEC = ROOT / 'site/sec-02.html'


def replace_figure(doc, n, markup):
    """Swap the <figure id="figure-n"> element for `markup`.

    Figures do not nest, so the first closing tag after the opening one is the
    right one and no depth counting is needed.
    """
    m = re.search(rf'<figure\b[^>]*\bid="figure-{n}"', doc)
    if not m:
        raise SystemExit(f'figure-{n} not found in {SEC.name}')
    end = doc.index('</figure>', m.start()) + len('</figure>')
    return doc[:m.start()] + markup.strip() + doc[end:]


def main():
    doc = SEC.read_text()
    css, done = [], []

    for n in range(2, 7):
        f = FIGS / f'figure-{n}.html'
        if not f.exists():
            continue
        doc = replace_figure(doc, n, f.read_text())
        done.append(n)

        c = FIGS / f'figure-{n}.css'
        if c.exists() and c.read_text().strip():
            css.append(f'/* ---- figure {n} ---- */\n' + c.read_text().strip())

    SEC.write_text(doc)

    out = ROOT / 'assets/figures.css'
    out.write_text('/* Generated by tools/install-figures.py from site/figures/*.css.\n'
                   '   Edit the per-figure file, not this one. */\n\n'
                   + '\n\n'.join(css) + '\n')

    left = [n for n in range(2, 7) if n not in done]
    print(f'installed  : {done or "none"}')
    print(f'still todo : {left or "none"}')
    print(f'css        : {len(css)} figure(s) -> {out}')


if __name__ == '__main__':
    main()
